[package]
name = "nalgebra-rand-mvn"
version = "0.1.0"
authors = ["Andrew Straw <strawman@astraw.com>"]
edition = "2018"

[dependencies]
nalgebra = "0.20"
rand = "0.7"
rand_distr = "0.2.1"

[dev-dependencies]
approx = "0.3"
