[package]
name = "nalgebra-rand-mvn"
description = "Random multi-variate normal generation using nalgebra"
version = "0.1.0"
authors = ["Andrew Straw <strawman@astraw.com>"]
edition = "2018"

[dependencies]
nalgebra = "0.24"
rand = "0.7"
rand_distr = "0.2.1"

[dev-dependencies]
approx = "0.4"
